version: '3.8'

services:

  react-app:
    restart: unless-stopped
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
  db:
    image: mysql:8.0.33
    container_name: mysql_database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldb-volume:/var/lib/mysql
    ports:
      - 3306:3306
  db-server:
    restart: unless-stopped
    build: ./server
    volumes:
      - ./server:/opt/db/server
      - /opt/db/server/node_modules
    depends_on:
      - db
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}

volumes:
  mysqldb-volume: