version: '3.4'

services:
  db:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldb-volume:/var/lib/mysql
    ports:
      - 8080:8080

  db-server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      volumes: 



volumes:
  mysqldb-volume: